version: '3.8'

services:
  app:
    build: .
    image: dafal/ip2locationlite-api:latest
    ports:
      - "127.0.0.1:4567:4567"
    volumes:
      - .:/usr/src/app
    environment:
      - RACK_ENV=production
      - IP2LOCATION_TOKEN=your-token-here